# crates/exocortex-cluster/Cargo.toml
[package]
name    = "exocortex-cluster"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
prost = { workspace = true }
subtle = { workspace = true }
futures = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
smol_str = { workspace = true }
exocortex-kernel = { workspace = true }
exocortex-wire = { workspace = true }
exocortex-storage = { workspace = true }
redis = { workspace = true }
chitchat = { workspace = true }
hmac = { workspace = true }
sha2 = { workspace = true }
axum = { workspace = true }
eventsource-client = { workspace = true }

[features]
integration = []

[dev-dependencies]
exocortex-server = { workspace = true }
chrono = { workspace = true }
serde_json = { workspace = true }
exocortex-pack-dev-v1 = { workspace = true }
tokio = { workspace = true }
