# crates/exocortex-reasoning/Cargo.toml
[package]
name    = "exocortex-reasoning"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
exocortex-kernel = { workspace = true }
exocortex-pack-dev-v1 = { workspace = true }
crepe = { workspace = true }
steel-core = { workspace = true }
